version: "3.8"

services:
  stock-api-db:
    image: postgres:14
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest

    networks:
      - stock-api

networks:
  stock-api: